### ISSUE TITLE
TRIVIAL BUG: Screen Scrolls when using Arrow Key Controls in Game (found during Alpha Testing Portion of Collaboration)

### ISSUE THREAD

**Issue by crw24** [LameLemon/CrimeHunter#103]
I think that this is a trivial bug, but I wanted to bring it up as it is a bit annoying. When you are playing the game with the keyboard controls (arrows keys) the screen scrolls up and down a little bit every time you push in the other direction, this doesn't really hamper game play but is bothersome nonetheless

**Comment by LameLemon** [comment]
Thanks for reporting, I've noticed this too, it will be rectified before the beta.
