### ISSUE TITLE
Small feature request

### ISSUE THREAD

**Issue by silentaim** [LameLemon/CrimeHunter#145]
While working on the project I noticed two small issues that can make the game a lot more fun. 

1. The bullets are hard to see, is it possible to make them a little bigger or perhaps add some sort of effects?

2. Can you show your ultimate status somewhere? I had no idea the ultimate even existed until I saw the help menu.

Just some suggestions, the ultimate makes the game a lot more fun 👍

**Comment by LameLemon** [comment]
Thank you for the suggestions, we will be addressing the issue in the official release.
