### ISSUE TITLE
"menu" button 

### ISSUE THREAD

**Issue by KemoAli** [LameLemon/CrimeHunter#150]
"menu" button does not respond when pressed. To see this just narrow the screen until the button appears at the top left corner and then press on it.

**Comment by LameLemon** [comment]
Thank you for reporting this, it seems to be on all devices with a smaller screen as well as when you reduce the browser size on a computer. I will look into this.

**Comment by LameLemon** [comment]
Seems like the issue was resolved but the changes were not deployed onto the site. The website has been updated and the menu button works on smaller screens. #125
