### ISSUE TITLE
Add a way to catch up to the red car

### ISSUE THREAD

**Issue by i-r-a** [LameLemon/CrimeHunter#152]
Currently as soon as it's off the screen you've lost but you still have to drive to the end of the level. It'd be nice if you either had a way to catch up, or there were multiple opportunities to get a kill before the end of the level, or it just gave you a game over after the red car got too far away from you, instead of going through the entirety of the level, knowing that you can't win.

**Comment by darasy** [comment]
Yes! That is a good request. 

To catch up, for now, the player can press the X-button to speed up.

We are thinking of putting some conditions for the player to win or lose such as put timing for every level. If any of the enemy have reached the finish line before the player, we plan to give a game over immediately.

Thank you for your request! We will take this into our consideration for future development.
