### ISSUE TITLE
Allow boss attack player

### ISSUE THREAD

**Issue by sunyizhou** [LameLemon/CrimeHunter#174]
Allow boss attack player
1. boss attack deal 3 times damages than enemy bullet.
2. boss can attack more frequently.

**Comment by darasy** [comment]
You cannot close your issue by yourself

**Comment by darasy** [comment]
You cannot close your issue by yourself.

**Comment by darasy** [comment]
After a group decision, as we no longer use Boss in our game, we decided to close this issue as it is no longer relevant to what we need.
