### ISSUE TITLE
Have the NPC cars moves in random speed after the set time duration. 

### ISSUE THREAD

**Issue by darasy** [LameLemon/CrimeHunter#76]
In update function, we need to have NPC cars (Civils) moves in random speed (either faster, slower, or the same) after the time duration that we set (works something like when it moves within lanes randomly, where we use a varible K to work as a timer (the higher K the less it switches lanes, and the lower (to reasonable amount) the more it switches).

**Comment by crw24** [comment]
Just wanted to let you guys know that I was assigned to this issue and am going to be starting to take a look at it today

**Comment by darasy** [comment]
okay. Just let me know if you have any questions.

**Comment by crw24** [comment]
In your code you have comments you have a section of civilian car movement update, which describes the higher frequency movement in line with K but also civilians moving away from the player, which seems outside of this issue, but is in the same section. Am I meant to just address speed?

**Comment by crw24** [comment]
scratch that, I see now a function lower that fulfills the second clause

**Comment by darasy** [comment]
oh okay. You get that right. So in this section, I just need the NPC cars to have their speed change after the time, let's say N (the same as K).

**Comment by crw24** [comment]
Currently I have the civilian cars changing speeds every 5 seconds, either going faster, slower or the same. I have it so they have values, they either go 75, 50, or 25, do you want the actual value of the speed to be random as well as if they do change speeds?

**Comment by crw24** [comment]
Rereading the issue answered my question. I am putting up a pull request from my fork

**Comment by darasy** [comment]
You completed the task as described. That is enough for this stage.
