### ISSUE TITLE
Add different bullets, different items on the road for adding health or skipping levels.

### ISSUE THREAD

**Issue by JiayiZheng** [LameLemon/CrimeHunter#79]
1. In "assets/buttons/", there are two bullets png. Load these two image in "var loadState={}" from "js/load.js"
2. Create these two bullet object. Set object null in the beginning of "var playState={}" from "js/play.js"
3. In "var playState={}" from "js/play.js", add object into game, set random chance to show object.
4. Add bullet0 and bullet1, 1 in 5 chance of spawning.

**Comment by silentaim** [comment]
Working on this right now @JiayiZheng

**Comment by silentaim** [comment]
Completed @JiayiZheng , please view:
https://github.com/LameLemon/CrimeHunter/pull/144

This was actually really fun to work on.  Hopefully you like the new game objects.
