### ISSUE TITLE
Stationary Left and Right movement absent.

### ISSUE THREAD

**Issue by Manvijay** [LameLemon/CrimeHunter#83]
Minor Issue: The car can not move left or right if it's stationary. In other words, the game can be improved by letting the user move the vehicle right and left without making it mandatory to move it forward even if you just want to make it shift left or right.

**Comment by LameLemon** [comment]
Thank you for reporting. This was intentional to make the game a little harder, we are working on making the movements a bit smoother for the Beta release, allowing for smaller increments of forward movements when you move left or right.
