### ISSUE TITLE
Bug With Exiting the Game and Trying to Start Over

### ISSUE THREAD

**Issue by mhbiele** [LameLemon/CrimeHunter#84]
The first time I exited the page and came back my progress was saved and could be resumed. Each time I exited the game and opened it back up, I started from the beginning. I'm playing the game using Google Chrome as my browser on a Windows 10 system.

**Comment by LameLemon** [comment]
Thank you for reporting the bug, the save feature starts you off from the beginning of the level. For example, if you exit the game towards the middle of level 2, when you start again you will begin at the start of level 2. We thought of the beginning of each level and a checkpoint in the game.
